import type { QuestionCategory } from './game';

export interface Question {
  id: number;
  category: QuestionCategory;
  text: string;
  timer: number;
  options?: string[];
  correctOptionIndex?: number;
  flagUrl?: string;
  mathExpression?: string;
}

export function isMultipleChoiceQuestion(question: Question): boolean {
  const supportsQcm =
    question.category === 'Energy Intel'
    || question.category === 'Drapeaux'
    || question.category === 'Maths';

  return (
    supportsQcm
    && Array.isArray(question.options)
    && question.options.length >= 2
    && typeof question.correctOptionIndex === 'number'
    && question.correctOptionIndex >= 0
    && question.correctOptionIndex < question.options.length
  );
}

export function isFlagQuestion(question: Question): boolean {
  return (
    question.category === 'Drapeaux'
    && typeof question.flagUrl === 'string'
    && question.flagUrl.length > 0
    && isMultipleChoiceQuestion(question)
  );
}

export function isMathQuestion(question: Question): boolean {
  return (
    question.category === 'Maths'
    && typeof question.mathExpression === 'string'
    && question.mathExpression.length > 0
    && isMultipleChoiceQuestion(question)
  );
}

export const questions: Question[] = [
  { id: 1, category: 'Fast & Furious', text: 'Cite 5 apps que tu utilises trop sur ton tel.', timer: 8 },
  { id: 2, category: 'Fast & Furious', text: 'Donne 4 plats que tu commandes souvent en livraison.', timer: 9 },
  { id: 3, category: 'Fast & Furious', text: 'Nomme 5 marques de baskets en moins de 8 secondes.', timer: 8 },
  { id: 4, category: 'Fast & Furious', text: 'Cite 4 emoji que tu envoies tout le temps.', timer: 7 },
  { id: 5, category: 'Dilemme', text: "Vivre 1 an dans l'espace ou 1 an sous l'eau ?", timer: 30 },
  { id: 6, category: 'Dilemme', text: 'Ne plus jamais voyager ou ne plus jamais sortir le soir ?', timer: 25 },
  { id: 7, category: 'Dilemme', text: "Avoir toujours 10 minutes d'avance ou 10 minutes de retard ?", timer: 20 },
  { id: 8, category: 'Dilemme', text: "Partager ton historique internet ou tes notes vocales ?", timer: 20 },
  {
    id: 9,
    category: 'Energy Intel',
    text: 'Laquelle est une energie renouvelable ?',
    timer: 12,
    options: ['Charbon', 'Petrole', 'Hydraulique', 'Gaz naturel'],
    correctOptionIndex: 2,
  },
  {
    id: 10,
    category: 'Energy Intel',
    text: 'Quel dispositif transforme directement la lumiere du soleil en electricite ?',
    timer: 12,
    options: ['Eolienne', 'Panneau photovoltaique', 'Barrage', 'Chaudiere gaz'],
    correctOptionIndex: 1,
  },
  {
    id: 11,
    category: 'Energy Intel',
    text: 'Quelle source d energie est consideree comme fossile ?',
    timer: 10,
    options: ['Petrole', 'Soleil', 'Vent', 'Marees'],
    correctOptionIndex: 0,
  },
  {
    id: 12,
    category: 'Energy Intel',
    text: 'Quel gaz est principalement responsable de l effet de serre d origine humaine ?',
    timer: 12,
    options: ['Helium', 'Dioxyde de carbone', 'Neon', 'Argon'],
    correctOptionIndex: 1,
  },
  { id: 13, category: 'Espion Géo', text: 'Dans quel pays se trouve Reykjavik ?', timer: 10 },
  { id: 14, category: 'Espion Géo', text: 'Quelle ville est surnommee la ville eternelle ?', timer: 10 },
  { id: 15, category: 'Espion Géo', text: "Quel ocean se trouve a l'est de Madagascar ?", timer: 12 },
  { id: 16, category: 'Espion Géo', text: "Cite 3 pays d'Afrique de l'Ouest en 10 secondes.", timer: 10 },
  { id: 17, category: 'Perso', text: 'Ton talent inutile mais legendaire ?', timer: 18 },
  { id: 18, category: 'Perso', text: 'Le pire message envoye a la mauvaise personne ?', timer: 22 },
  { id: 19, category: 'Perso', text: 'Si on part en road trip demain, tu prends quoi en premier ?', timer: 20 },
  { id: 20, category: 'Perso', text: 'Ton excuse classique quand tu reponds en retard ?', timer: 16 },
  { id: 21, category: 'Fast & Furious', text: 'Cite 4 rappeurs francophones en moins de 7 secondes.', timer: 7 },
  { id: 22, category: 'Dilemme', text: 'Avoir un bouton pause sur la vie ou retour en arriere 30 secondes ?', timer: 24 },

  { id: 23, category: 'Fast & Furious', text: 'Cite 5 toppings de pizza en 8 secondes.', timer: 8 },
  { id: 24, category: 'Fast & Furious', text: 'Donne 4 sports olympiques en 7 secondes.', timer: 7 },
  { id: 25, category: 'Fast & Furious', text: 'Cite 5 capitales europeennes rapidement.', timer: 9 },
  { id: 26, category: 'Fast & Furious', text: 'Nomme 4 plateformes de streaming en 6 secondes.', timer: 6 },
  { id: 27, category: 'Fast & Furious', text: 'Cite 5 fruits rouges en moins de 8 secondes.', timer: 8 },
  { id: 28, category: 'Fast & Furious', text: 'Donne 4 marques de voiture electrique en 8 secondes.', timer: 8 },
  { id: 29, category: 'Fast & Furious', text: 'Cite 5 villes marocaines en 9 secondes.', timer: 9 },
  { id: 30, category: 'Fast & Furious', text: 'Nomme 4 films d animation connus en 7 secondes.', timer: 7 },
  { id: 31, category: 'Fast & Furious', text: 'Cite 5 mots qui commencent par la lettre B.', timer: 8 },
  { id: 32, category: 'Fast & Furious', text: 'Donne 4 boissons chaudes en 6 secondes.', timer: 6 },

  { id: 33, category: 'Dilemme', text: 'Toujours chanter au lieu de parler ou toujours danser en marchant ?', timer: 22 },
  { id: 34, category: 'Dilemme', text: 'Avoir internet ultra lent ou batterie a 5% en permanence ?', timer: 22 },
  { id: 35, category: 'Dilemme', text: 'Perdre ton tel 1 mois ou perdre ton portefeuille 1 mois ?', timer: 24 },
  { id: 36, category: 'Dilemme', text: 'Manger epice toute ta vie ou manger sans sel toute ta vie ?', timer: 24 },
  { id: 37, category: 'Dilemme', text: 'Dormir 4h par nuit ou te lever a 5h tous les jours ?', timer: 22 },
  { id: 38, category: 'Dilemme', text: 'Avoir une memoire parfaite ou une creativite infinie ?', timer: 20 },
  { id: 39, category: 'Dilemme', text: 'Etre celebre mais sans vie privee ou inconnu mais tres riche ?', timer: 24 },
  { id: 40, category: 'Dilemme', text: 'Ne plus jamais ecouter de musique ou ne plus jamais regarder de series ?', timer: 23 },
  { id: 41, category: 'Dilemme', text: 'Avoir toujours trop chaud ou toujours trop froid ?', timer: 20 },
  { id: 42, category: 'Dilemme', text: 'Vivre sans cafe ou vivre sans chocolat ?', timer: 20 },

  {
    id: 43,
    category: 'Energy Intel',
    text: 'Quel appareil mesure la puissance electrique en watts ?',
    timer: 12,
    options: ['Amperemetre', 'Wattmetre', 'Voltmeter', 'Thermometre'],
    correctOptionIndex: 1,
  },
  {
    id: 44,
    category: 'Energy Intel',
    text: 'Quelle energie utilise la chaleur interne de la Terre ?',
    timer: 12,
    options: ['Geothermie', 'Biomasse', 'Hydrogene', 'Petrole'],
    correctOptionIndex: 0,
  },
  {
    id: 45,
    category: 'Energy Intel',
    text: 'Dans une maison, quel appareil consomme souvent le plus sur l annee ?',
    timer: 12,
    options: ['Refrigerateur', 'Chargeur de telephone', 'Ampoule LED', 'Routeur wifi'],
    correctOptionIndex: 0,
  },
  {
    id: 46,
    category: 'Energy Intel',
    text: 'Que signifie kWh ?',
    timer: 12,
    options: ['Kilowatt heure', 'Kilo watt hertz', 'Kelvin watt heure', 'Kilo watt hydraulique'],
    correctOptionIndex: 0,
  },
  {
    id: 47,
    category: 'Energy Intel',
    text: 'Quelle energie est produite par la force du vent ?',
    timer: 10,
    options: ['Solaire', 'Eolienne', 'Nucleaire', 'Geothermique'],
    correctOptionIndex: 1,
  },
  {
    id: 48,
    category: 'Energy Intel',
    text: 'Quel geste economise generalement de l energie a la maison ?',
    timer: 10,
    options: ['Laisser les chargeurs branches', 'Baisser le chauffage de 1 degre', 'Ouvrir les fenetres avec chauffage allume', 'Allumer toutes les lampes'],
    correctOptionIndex: 1,
  },
  {
    id: 49,
    category: 'Energy Intel',
    text: 'Lequel est un combustible nucleaire courant ?',
    timer: 12,
    options: ['Uranium', 'Lithium', 'Silicium', 'Calcium'],
    correctOptionIndex: 0,
  },
  {
    id: 50,
    category: 'Energy Intel',
    text: 'Une batterie stocke principalement quelle forme d energie ?',
    timer: 10,
    options: ['Mecanique', 'Chimique', 'Sonore', 'Nucleaire'],
    correctOptionIndex: 1,
  },

  { id: 51, category: 'Espion Géo', text: 'Quelle est la capitale du Canada ?', timer: 10 },
  { id: 52, category: 'Espion Géo', text: 'Quel desert couvre une grande partie de l Algerie ?', timer: 10 },
  { id: 53, category: 'Espion Géo', text: 'Quelle est la capitale du Japon ?', timer: 9 },
  { id: 54, category: 'Espion Géo', text: 'Dans quel pays se trouve la ville de Porto ?', timer: 10 },
  { id: 55, category: 'Espion Géo', text: 'Quel fleuve traverse Paris ?', timer: 8 },
  { id: 56, category: 'Espion Géo', text: 'Quel pays a pour capitale Nairobi ?', timer: 10 },
  { id: 57, category: 'Espion Géo', text: 'Quel est le plus grand ocean de la planete ?', timer: 10 },
  { id: 58, category: 'Espion Géo', text: 'Quelle chaine de montagnes separe souvent France et Espagne ?', timer: 10 },
  { id: 59, category: 'Espion Géo', text: 'Quelle est la capitale de l Australie ?', timer: 10 },
  { id: 60, category: 'Espion Géo', text: 'Dans quel pays se trouve Marrakech ?', timer: 8 },

  { id: 61, category: 'Perso', text: 'Ton snack coupable prefere apres minuit ?', timer: 18 },
  { id: 62, category: 'Perso', text: 'La chanson que tu connais par coeur sans l avouer ?', timer: 16 },
  { id: 63, category: 'Perso', text: 'Ton plus gros caprice inutile recent ?', timer: 18 },
  { id: 64, category: 'Perso', text: 'Le super pouvoir le plus pratique pour toi au quotidien ?', timer: 20 },
  { id: 65, category: 'Perso', text: 'Ton meilleur souvenir de voyage en 1 phrase ?', timer: 20 },
  { id: 66, category: 'Perso', text: 'Ton excuse preferee pour annuler un plan ?', timer: 18 },
  { id: 67, category: 'Perso', text: 'Le metier que tu aurais voulu tester 1 semaine ?', timer: 20 },
  { id: 68, category: 'Perso', text: 'Le petit detail qui peut te mettre de bonne humeur direct ?', timer: 18 },
  { id: 69, category: 'Perso', text: 'Ta serie comfort a rewatch sans fatigue ?', timer: 16 },
  { id: 70, category: 'Perso', text: 'Ton objectif perso le plus fun pour cette annee ?', timer: 20 },

  {
    id: 71,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/fr.png',
    options: ['Italie', 'France', 'Pays-Bas', 'Belgique'],
    correctOptionIndex: 1,
  },
  {
    id: 72,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/br.png',
    options: ['Argentine', 'Bolivie', 'Bresil', 'Colombie'],
    correctOptionIndex: 2,
  },
  {
    id: 73,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/jp.png',
    options: ['Coree du Sud', 'Japon', 'Bangladesh', 'Vietnam'],
    correctOptionIndex: 1,
  },
  {
    id: 74,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/de.png',
    options: ['Belgique', 'Autriche', 'Allemagne', 'Hongrie'],
    correctOptionIndex: 2,
  },
  {
    id: 75,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/ma.png',
    options: ['Maroc', 'Tunisie', 'Algerie', 'Egypte'],
    correctOptionIndex: 0,
  },
  {
    id: 76,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/dz.png',
    options: ['Pakistan', 'Algerie', 'Arabie saoudite', 'Libye'],
    correctOptionIndex: 1,
  },
  {
    id: 77,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/sn.png',
    options: ['Mali', 'Senegal', 'Guinee', 'Cameroun'],
    correctOptionIndex: 1,
  },
  {
    id: 78,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/gh.png',
    options: ['Ghana', 'Ethiopie', 'Kenya', 'Togo'],
    correctOptionIndex: 0,
  },
  {
    id: 79,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/no.png',
    options: ['Danemark', 'Finlande', 'Norvege', 'Suede'],
    correctOptionIndex: 2,
  },
  {
    id: 80,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/th.png',
    options: ['Cambodge', 'Thailande', 'Laos', 'Myanmar'],
    correctOptionIndex: 1,
  },
  {
    id: 81,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/it.png',
    options: ['Mexique', 'Irlande', 'Italie', 'Bulgarie'],
    correctOptionIndex: 2,
  },
  {
    id: 82,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/es.png',
    options: ['Espagne', 'Portugal', 'Roumanie', 'Andorre'],
    correctOptionIndex: 0,
  },
  {
    id: 83,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/gb.png',
    options: ['Australie', 'Nouvelle-Zelande', 'Royaume-Uni', 'Etats-Unis'],
    correctOptionIndex: 2,
  },
  {
    id: 84,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/us.png',
    options: ['Liberia', 'Etats-Unis', 'Chili', 'Malaisie'],
    correctOptionIndex: 1,
  },
  {
    id: 85,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/ca.png',
    options: ['Autriche', 'Perou', 'Canada', 'Suisse'],
    correctOptionIndex: 2,
  },
  {
    id: 86,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/mx.png',
    options: ['Italie', 'Mexique', 'Hongrie', 'Iran'],
    correctOptionIndex: 1,
  },
  {
    id: 87,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/ar.png',
    options: ['Argentine', 'Uruguay', 'Paraguay', 'Guatemala'],
    correctOptionIndex: 0,
  },
  {
    id: 88,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/in.png',
    options: ['Niger', 'Inde', 'Cote d Ivoire', 'Irlande'],
    correctOptionIndex: 1,
  },
  {
    id: 89,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/cn.png',
    options: ['Vietnam', 'Chine', 'Maroc', 'Tunisie'],
    correctOptionIndex: 1,
  },
  {
    id: 90,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/tr.png',
    options: ['Turquie', 'Tunisie', 'Algerie', 'Pakistan'],
    correctOptionIndex: 0,
  },
  {
    id: 91,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/bt.png',
    options: ['Bhoutan', 'Nepal', 'Mongolie', 'Kazakhstan'],
    correctOptionIndex: 0,
  },
  {
    id: 92,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/er.png',
    options: ['Erythree', 'Djibouti', 'Ethiopie', 'Somalie'],
    correctOptionIndex: 0,
  },
  {
    id: 93,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/vu.png',
    options: ['Fidji', 'Vanuatu', 'Samoa', 'Tonga'],
    correctOptionIndex: 1,
  },
  {
    id: 94,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/la.png',
    options: ['Cambodge', 'Laos', 'Thailande', 'Myanmar'],
    correctOptionIndex: 1,
  },
  {
    id: 95,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/mn.png',
    options: ['Mongolie', 'Kazakhstan', 'Kirghizistan', 'Ouzbekistan'],
    correctOptionIndex: 0,
  },
  {
    id: 96,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/np.png',
    options: ['Bhoutan', 'Nepal', 'Inde', 'Bangladesh'],
    correctOptionIndex: 1,
  },
  {
    id: 97,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/ge.png',
    options: ['Armenie', 'Georgie', 'Azerbaidjan', 'Bulgarie'],
    correctOptionIndex: 1,
  },
  {
    id: 98,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/am.png',
    options: ['Armenie', 'Lituanie', 'Bolivie', 'Hongrie'],
    correctOptionIndex: 0,
  },
  {
    id: 99,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/kg.png',
    options: ['Tadjikistan', 'Kirghizistan', 'Mongolie', 'Nepal'],
    correctOptionIndex: 1,
  },
  {
    id: 100,
    category: 'Drapeaux',
    text: 'De quel pays est ce drapeau ?',
    timer: 10,
    flagUrl: 'https://flagcdn.com/w160/ao.png',
    options: ['Angola', 'Mozambique', 'Zimbabwe', 'Zambie'],
    correctOptionIndex: 0,
  },

  {
    id: 101,
    category: 'Maths',
    text: 'Combien vaut 17 x 8 ?',
    timer: 20,
    mathExpression: '17 x 8 = ?',
    options: ['126', '134', '136', '142'],
    correctOptionIndex: 2,
  },
  {
    id: 102,
    category: 'Maths',
    text: 'Quelle est la valeur de x ?',
    timer: 20,
    mathExpression: '3x + 7 = 22',
    options: ['4', '5', '6', '7'],
    correctOptionIndex: 1,
  },
  {
    id: 103,
    category: 'Maths',
    text: 'Trouve le prochain nombre de la suite.',
    timer: 20,
    mathExpression: '2, 5, 11, 23, ?',
    options: ['35', '41', '47', '49'],
    correctOptionIndex: 2,
  },
  {
    id: 104,
    category: 'Maths',
    text: 'Combien vaut 15% de 240 ?',
    timer: 20,
    mathExpression: '0.15 x 240',
    options: ['30', '34', '36', '40'],
    correctOptionIndex: 2,
  },
  {
    id: 105,
    category: 'Maths',
    text: 'Additionne les fractions.',
    timer: 20,
    mathExpression: '1/2 + 1/4 = ?',
    options: ['2/3', '3/4', '4/5', '1'],
    correctOptionIndex: 1,
  },
  {
    id: 106,
    category: 'Maths',
    text: 'Aire d un rectangle 12 par 7 ?',
    timer: 20,
    mathExpression: 'A = L x l',
    options: ['72', '84', '91', '96'],
    correctOptionIndex: 1,
  },
  {
    id: 107,
    category: 'Maths',
    text: 'Probabilite d obtenir pile sur une piece equilibree ?',
    timer: 20,
    mathExpression: 'P(pile) = ?',
    options: ['1/4', '1/3', '1/2', '2/3'],
    correctOptionIndex: 2,
  },
  {
    id: 108,
    category: 'Maths',
    text: 'Perimetre d un carre de cote 9 ?',
    timer: 20,
    mathExpression: 'P = 4c',
    options: ['27', '32', '36', '40'],
    correctOptionIndex: 2,
  },
  {
    id: 109,
    category: 'Maths',
    text: 'Quelle est la valeur de x ?',
    timer: 20,
    mathExpression: '5x - 10 = 40',
    options: ['8', '9', '10', '11'],
    correctOptionIndex: 2,
  },
  {
    id: 110,
    category: 'Maths',
    text: 'Combien vaut 19 + 27 ?',
    timer: 20,
    mathExpression: '19 + 27 = ?',
    options: ['44', '45', '46', '47'],
    correctOptionIndex: 2,
  },
  {
    id: 111,
    category: 'Maths',
    text: 'Quel est le prochain nombre ?',
    timer: 20,
    mathExpression: '3, 6, 12, 24, ?',
    options: ['36', '42', '48', '54'],
    correctOptionIndex: 2,
  },
  {
    id: 112,
    category: 'Maths',
    text: 'Combien vaut 12% de 150 ?',
    timer: 20,
    mathExpression: '0.12 x 150',
    options: ['15', '18', '20', '24'],
    correctOptionIndex: 1,
  },
  {
    id: 113,
    category: 'Maths',
    text: 'Soustrais les fractions.',
    timer: 20,
    mathExpression: '5/6 - 1/3 = ?',
    options: ['1/6', '1/2', '2/3', '3/4'],
    correctOptionIndex: 1,
  },
  {
    id: 114,
    category: 'Maths',
    text: 'Aire d un triangle base 10 hauteur 6 ?',
    timer: 20,
    mathExpression: 'A = (b x h) / 2',
    options: ['24', '30', '36', '40'],
    correctOptionIndex: 1,
  },
  {
    id: 115,
    category: 'Maths',
    text: 'Probabilite de tirer une carte coeur dans un jeu de 52 cartes ?',
    timer: 20,
    mathExpression: '13 coeurs sur 52 cartes',
    options: ['1/2', '1/3', '1/4', '1/5'],
    correctOptionIndex: 2,
  },
  {
    id: 116,
    category: 'Maths',
    text: 'Quelle est la valeur de x ?',
    timer: 20,
    mathExpression: '2x + 9 = 25',
    options: ['6', '7', '8', '9'],
    correctOptionIndex: 2,
  },
  {
    id: 117,
    category: 'Maths',
    text: 'Combien vaut 144 / 12 ?',
    timer: 20,
    mathExpression: '144 / 12 = ?',
    options: ['10', '11', '12', '13'],
    correctOptionIndex: 2,
  },
  {
    id: 118,
    category: 'Maths',
    text: 'Trouve le prochain nombre.',
    timer: 20,
    mathExpression: '1, 4, 9, 16, ?',
    options: ['20', '24', '25', '27'],
    correctOptionIndex: 2,
  },
  {
    id: 119,
    category: 'Maths',
    text: 'Combien vaut 35% de 80 ?',
    timer: 20,
    mathExpression: '0.35 x 80',
    options: ['24', '26', '28', '30'],
    correctOptionIndex: 2,
  },
  {
    id: 120,
    category: 'Maths',
    text: 'Multiplie les fractions.',
    timer: 20,
    mathExpression: '(2/3) x (3/5) = ?',
    options: ['2/5', '3/5', '4/5', '1/2'],
    correctOptionIndex: 0,
  },
  {
    id: 121,
    category: 'Maths',
    text: 'Perimetre d un rectangle 11 par 4 ?',
    timer: 20,
    mathExpression: 'P = 2(L + l)',
    options: ['26', '28', '30', '32'],
    correctOptionIndex: 2,
  },
  {
    id: 122,
    category: 'Maths',
    text: 'Quelle est la valeur de x ?',
    timer: 20,
    mathExpression: '4x = 52',
    options: ['11', '12', '13', '14'],
    correctOptionIndex: 2,
  },
  {
    id: 123,
    category: 'Maths',
    text: 'Combien vaut 7^2 - 5^2 ?',
    timer: 20,
    mathExpression: '49 - 25',
    options: ['22', '24', '26', '28'],
    correctOptionIndex: 1,
  },
  {
    id: 124,
    category: 'Maths',
    text: 'Trouve le prochain nombre.',
    timer: 20,
    mathExpression: '10, 20, 17, 34, 31, ?',
    options: ['50', '55', '62', '68'],
    correctOptionIndex: 2,
  },
  {
    id: 125,
    category: 'Maths',
    text: 'Combien vaut 22% de 50 ?',
    timer: 20,
    mathExpression: '0.22 x 50',
    options: ['9', '10', '11', '12'],
    correctOptionIndex: 2,
  },
  {
    id: 126,
    category: 'Maths',
    text: 'Additionne les fractions.',
    timer: 20,
    mathExpression: '3/8 + 1/8 = ?',
    options: ['1/2', '3/4', '5/8', '2/3'],
    correctOptionIndex: 0,
  },
  {
    id: 127,
    category: 'Maths',
    text: 'Aire d un disque de rayon 3 (pi ~ 3.14) ?',
    timer: 20,
    mathExpression: 'A = pi r^2',
    options: ['18.84', '25.12', '28.26', '31.40'],
    correctOptionIndex: 2,
  },
  {
    id: 128,
    category: 'Maths',
    text: 'Probabilite de tirer une boule rouge parmi 3 rouges et 2 bleues ?',
    timer: 20,
    mathExpression: 'P(rouge) = 3 / 5',
    options: ['2/5', '3/5', '1/2', '4/5'],
    correctOptionIndex: 1,
  },
  {
    id: 129,
    category: 'Maths',
    text: 'Quelle est la valeur de x ?',
    timer: 20,
    mathExpression: 'x/4 + 3 = 8',
    options: ['16', '18', '20', '22'],
    correctOptionIndex: 2,
  },
  {
    id: 130,
    category: 'Maths',
    text: 'Combien vaut 18 x 14 ?',
    timer: 20,
    mathExpression: '18 x 14 = ?',
    options: ['242', '252', '262', '272'],
    correctOptionIndex: 1,
  },
];
